In [53]:
import numpy as np

X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y=np.array([[1],[1],[0]])

def sigmoid(x):
    return 1/(1+np.exp(-x))

def der_sigmoid(x):
    return x*(1-x)

epoch= 10000
lr =0.5

In [54]:
inputLayerNeurons = X.shape[1]     #no of features eg: 4 in [1,0,1,0]

In [55]:
hiddenLayerNeurons = 3
outputLayerNeurons = 1

In [56]:
wh=np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))   #default range is (0,1)
wh

array([[ 0.83672512,  0.03495992,  0.70661848],
       [ 0.63271423,  0.09280188,  0.46784521],
       [ 0.36840291,  0.69561679,  0.96487328],
       [ 0.61701663,  0.72248416,  0.94388893]])

In [57]:
bh=np.random.uniform(size=(1,hiddenLayerNeurons))
bh

array([[ 0.21814325,  0.75993842,  0.9197238 ]])

In [58]:
wout=np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))   #default range is (0,1) size(r,c)
wout

array([[ 0.22930414],
       [ 0.37638388],
       [ 0.8660884 ]])

In [59]:
bout=np.random.uniform(size=(1,outputLayerNeurons))
bout

array([[ 0.67947708]])

In [60]:
#hiddenLayerInput = np.dot(X,wh)
#hiddenLayerInput

In [61]:
#hiddenLayerInput +=bh 
#hiddenLayerInput

In [68]:
for i in range(epoch):
    hiddenLayerInput = np.dot(X,wh)
    hiddenLayerInput += bh    
    hiddenLayerActivation = sigmoid(hiddenLayerInput)
    outputLayerInput = np.dot(hiddenLayerActivation,wout)
    outputLayerInput +=bout
    output = sigmoid(outputLayerInput)
    E = y - output
    slopeOfOutputLayer = der_sigmoid(output)
    d_output = E * slopeOfOutputLayer
    slopeOfHiddenLayer = der_sigmoid(hiddenLayerActivation)
    errorAtHiddenlayer = d_output.dot(wout.T)
    d_hidden= errorAtHiddenlayer *slopeOfHiddenLayer
    wout +=hiddenLayerActivation.T.dot(d_output)*lr
    bout +=np.sum(d_output,axis=0,keepdims=True)*lr
    wh   +=X.T.dot(d_hidden)*lr
    bh   +=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [69]:
print(output)

[[ 0.99701172]
 [ 0.9959937 ]
 [ 0.00525944]]


In [41]:
#slopeOfOutputLayer 
errorAtHiddenlayer

array([[ 0.00890295,  0.00559898,  0.00121664],
       [ 0.00714748,  0.00449498,  0.00097674],
       [-0.07333309, -0.0461185 , -0.01002135]])

In [38]:
wout.shape

(3, 1)

In [39]:
wout.T.shape

(1, 3)